name: Changelog
on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-ruby@v1
      - run: gem install github_changelog_generator
      - run: github_changelog_generator -u sidvishnoi -p respec-xref-route --no-unreleased
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(CHANGELOG): regenerate"
          title: "chore(CHANGELOG): regenerate"
          branch: regenerate-changelog
