name: npm publish
on:
  release:
    types: [published]
jobs:
  publish-npm:
    name: Build and Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --ignore-scripts
      - name: Build and Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
